name: detect item changes

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  detect_item_changes:
    runs-on: ubuntu-latest

    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }}

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Detect item changes
      id: detect_changes
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
      run: |
        python item-detection.py > detect.log
        echo "==== Detection Output ===="
        cat detect.log
        # 🆕 Check if detection script logged something like "CHANGES_FOUND"
        if grep -q "CHANGES_FOUND" detect.log; then
          echo "changes=true" >> $GITHUB_OUTPUT
        else
          echo "changes=false" >> $GITHUB_OUTPUT
        fi

    - name: Update previous data
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add previous_item_data.json
        git commit -m "update previous_item_data.json" || echo "No changes to commit"
        git push || echo "No changes to push"

    # 🆕 Only trigger changelog generation when there are actual changes
    - name: Trigger changelog generation in Wynnpool
      if: steps.detect_changes.outputs.changes == 'true'
      run: |
        echo "Triggering changelog generation in Wynnpool..."
        curl -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.WYNNPOOL }}" \
          https://api.github.com/repos/AiverAiva/Wynnpool/actions/workflows/generate-changelog.yml/dispatches \
          -d '{"ref":"main"}'
