name: detect item changes
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: 

jobs:
  detect_item_changes:
    runs-on: ubuntu-latest

    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }} # Secret to store MongoDB URI

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Detect item changes
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
      run: |
        python item-detection.py
    
    - name: Update previous data
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add previous_item_data.json
        git commit -m "update previous_item_data.json" || echo "No changes to commit"
        git push || echo "No changes to push"
