name: Keep GitHub Actions Active

on:
  schedule:
    - cron: '0 0 * * 7'
  workflow_dispatch: 

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Update Timestamp
        run: |
          date > keepalive.txt
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add keepalive.txt
          git commit -m "Keepalive update"
          git push
