name: sync item database
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: 

jobs:
  sync_items:
    runs-on: ubuntu-latest

    env:
      MONGODB_URI: ${{ secrets.MONGODB_URI }} # Secret to store MongoDB URI

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: sync items
      env:
        MONGODB_URI: ${{ secrets.MONGODB_URI }}
      run: |
        python sync_items.py
